// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(neutrinoFFI)
import neutrinoFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_neutrino_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_neutrino_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureNeutrinoInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol NeutrinoHandleProtocol: AnyObject, Sendable {
    
    /**
     * Push a control command to the running server. Fire-and-forget: returns
     * immediately and never blocks — the channel is unbounded, so the sync
     * `UnboundedSender::send` never awaits, which is what lets this be called
     * safely from the FFI/JNI thread (a bounded channel would force either an
     * `async fn` across the boundary or a backpressure-drop policy). A send
     * after the server has already stopped (receiver dropped) is a silent
     * no-op.
     */
    func command(command: Command) 
    
    /**
     * A single-shot snapshot of every peer discovered over the BLE mesh, sorted
     * by `(display_name, server_name)`. Not live — the host re-calls to refresh.
     * A non-blocking in-memory read (like `server_name`), so it is safe to call
     * from the FFI/JNI thread. Empty on a build without BLE discovery, or before
     * the first scan has landed any peers.
     */
    func discoveredPeers()  -> [DiscoveredPeer]
    
    /**
     * Whether a capture is currently running — drives the Settings toggle state.
     */
    func isCapturing()  -> Bool
    
    /**
     * Reset outbound retry backoff and retry now. Convenience for
     * `command(Command::KickBackoff)`; the host calls this when device
     * connectivity is restored so backed-off destinations reconnect promptly.
     */
    func kickBackoff() 
    
    /**
     * The fatal error the server exited with, or `None` while it is starting or
     * running normally. The host polls this alongside `server_name()`: a
     * `Some(server_name)` means "ready", a `Some(last_error)` means "refused to
     * start — show this message in a dialog". A non-blocking in-memory read
     * (like `server_name`), safe to call from the FFI/JNI thread. Startup
     * failures that used to only reach logcat (identity mismatch, bad config,
     * bind failure) are now observable by the host.
     */
    func lastError()  -> String?
    
    /**
     * The server's resolved federation name — its derived node id, or `None`
     * until the server has booted and resolved its identity (so the host can
     * distinguish "not ready yet" from a value rather than racing on an empty
     * string). Since the embedded server takes no configured name, this is
     * how the host learns the name to build user ids
     * (`@localpart:server_name`).
     */
    func serverName()  -> String?
    
    /**
     * Gracefully stop the server. Convenience for `command(Command::Shutdown)`;
     * preserves the pre-existing FFI method so existing Android callers keep
     * working unchanged.
     */
    func shutdown() 
    
    /**
     * Start mirroring every federation HTTP request/response into a
     * Wireshark-readable pcap at `path` (an absolute path in host-owned
     * storage, e.g. app-specific external storage so it is `adb pull`-able).
     * The capture is HTTP/JSON — what a `tcpdump -i lo` on a desktop would
     * have shown of the two loopback legs, which Android cannot capture
     * itself. Errors if the file can't be opened. Calling it while already
     * capturing rotates to the new file. A non-blocking control call, safe
     * from the FFI/JNI thread.
     */
    func startCapture(path: String) throws 
    
    /**
     * Stop capturing and flush + close the file before returning, so it is
     * immediately ready to `adb pull`. Returns whether a capture was running.
     * Idempotent.
     */
    func stopCapture()  -> Bool
    
}
open class NeutrinoHandle: NeutrinoHandleProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_neutrino_fn_clone_neutrinohandle(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_neutrino_fn_free_neutrinohandle(handle, $0) }
    }

    

    
    /**
     * Push a control command to the running server. Fire-and-forget: returns
     * immediately and never blocks — the channel is unbounded, so the sync
     * `UnboundedSender::send` never awaits, which is what lets this be called
     * safely from the FFI/JNI thread (a bounded channel would force either an
     * `async fn` across the boundary or a backpressure-drop policy). A send
     * after the server has already stopped (receiver dropped) is a silent
     * no-op.
     */
open func command(command: Command)  {try! rustCall() {
    uniffi_neutrino_fn_method_neutrinohandle_command(
            self.uniffiCloneHandle(),
        FfiConverterTypeCommand_lower(command),$0
    )
}
}
    
    /**
     * A single-shot snapshot of every peer discovered over the BLE mesh, sorted
     * by `(display_name, server_name)`. Not live — the host re-calls to refresh.
     * A non-blocking in-memory read (like `server_name`), so it is safe to call
     * from the FFI/JNI thread. Empty on a build without BLE discovery, or before
     * the first scan has landed any peers.
     */
open func discoveredPeers() -> [DiscoveredPeer]  {
    return try!  FfiConverterSequenceTypeDiscoveredPeer.lift(try! rustCall() {
    uniffi_neutrino_fn_method_neutrinohandle_discovered_peers(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Whether a capture is currently running — drives the Settings toggle state.
     */
open func isCapturing() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_neutrino_fn_method_neutrinohandle_is_capturing(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Reset outbound retry backoff and retry now. Convenience for
     * `command(Command::KickBackoff)`; the host calls this when device
     * connectivity is restored so backed-off destinations reconnect promptly.
     */
open func kickBackoff()  {try! rustCall() {
    uniffi_neutrino_fn_method_neutrinohandle_kick_backoff(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * The fatal error the server exited with, or `None` while it is starting or
     * running normally. The host polls this alongside `server_name()`: a
     * `Some(server_name)` means "ready", a `Some(last_error)` means "refused to
     * start — show this message in a dialog". A non-blocking in-memory read
     * (like `server_name`), safe to call from the FFI/JNI thread. Startup
     * failures that used to only reach logcat (identity mismatch, bad config,
     * bind failure) are now observable by the host.
     */
open func lastError() -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_neutrino_fn_method_neutrinohandle_last_error(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * The server's resolved federation name — its derived node id, or `None`
     * until the server has booted and resolved its identity (so the host can
     * distinguish "not ready yet" from a value rather than racing on an empty
     * string). Since the embedded server takes no configured name, this is
     * how the host learns the name to build user ids
     * (`@localpart:server_name`).
     */
open func serverName() -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_neutrino_fn_method_neutrinohandle_server_name(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Gracefully stop the server. Convenience for `command(Command::Shutdown)`;
     * preserves the pre-existing FFI method so existing Android callers keep
     * working unchanged.
     */
open func shutdown()  {try! rustCall() {
    uniffi_neutrino_fn_method_neutrinohandle_shutdown(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Start mirroring every federation HTTP request/response into a
     * Wireshark-readable pcap at `path` (an absolute path in host-owned
     * storage, e.g. app-specific external storage so it is `adb pull`-able).
     * The capture is HTTP/JSON — what a `tcpdump -i lo` on a desktop would
     * have shown of the two loopback legs, which Android cannot capture
     * itself. Errors if the file can't be opened. Calling it while already
     * capturing rotates to the new file. A non-blocking control call, safe
     * from the FFI/JNI thread.
     */
open func startCapture(path: String)throws   {try rustCallWithError(FfiConverterTypeCaptureError_lift) {
    uniffi_neutrino_fn_method_neutrinohandle_start_capture(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(path),$0
    )
}
}
    
    /**
     * Stop capturing and flush + close the file before returning, so it is
     * immediately ready to `adb pull`. Returns whether a capture was running.
     * Idempotent.
     */
open func stopCapture() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_neutrino_fn_method_neutrinohandle_stop_capture(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNeutrinoHandle: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = NeutrinoHandle

    public static func lift(_ handle: UInt64) throws -> NeutrinoHandle {
        return NeutrinoHandle(unsafeFromHandle: handle)
    }

    public static func lower(_ value: NeutrinoHandle) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NeutrinoHandle {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: NeutrinoHandle, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNeutrinoHandle_lift(_ handle: UInt64) throws -> NeutrinoHandle {
    return try FfiConverterTypeNeutrinoHandle.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNeutrinoHandle_lower(_ value: NeutrinoHandle) -> UInt64 {
    return FfiConverterTypeNeutrinoHandle.lower(value)
}




/**
 * A peer the embedded server has discovered out of band (over the federation
 * medium's scan), for the host to render in a
 * Settings directory. Host-facing projection of
 * `neutrino_ctl::DiscoveredPeer` plus its `server_name` key; the localpart is
 * omitted (the host builds user ids itself from `server_name`).
 */
public struct DiscoveredPeer: Equatable, Hashable {
    /**
     * The peer's `server_name` (its 64-char hex node id).
     */
    public var serverName: String
    /**
     * The display name the peer advertised.
     */
    public var displayName: String
    /**
     * Wall-clock milliseconds of the scan snapshot that last saw this peer.
     * Uniform across all peers in a snapshot (see `discovered_peers`).
     */
    public var lastSeenMs: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The peer's `server_name` (its 64-char hex node id).
         */serverName: String, 
        /**
         * The display name the peer advertised.
         */displayName: String, 
        /**
         * Wall-clock milliseconds of the scan snapshot that last saw this peer.
         * Uniform across all peers in a snapshot (see `discovered_peers`).
         */lastSeenMs: UInt64) {
        self.serverName = serverName
        self.displayName = displayName
        self.lastSeenMs = lastSeenMs
    }

    

    
}

#if compiler(>=6)
extension DiscoveredPeer: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDiscoveredPeer: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DiscoveredPeer {
        return
            try DiscoveredPeer(
                serverName: FfiConverterString.read(from: &buf), 
                displayName: FfiConverterString.read(from: &buf), 
                lastSeenMs: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: DiscoveredPeer, into buf: inout [UInt8]) {
        FfiConverterString.write(value.serverName, into: &buf)
        FfiConverterString.write(value.displayName, into: &buf)
        FfiConverterUInt64.write(value.lastSeenMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDiscoveredPeer_lift(_ buf: RustBuffer) throws -> DiscoveredPeer {
    return try FfiConverterTypeDiscoveredPeer.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDiscoveredPeer_lower(_ value: DiscoveredPeer) -> RustBuffer {
    return FfiConverterTypeDiscoveredPeer.lower(value)
}


/**
 * FFI-facing server configuration. Mirrors `neutrino_ctl::Config` so EX
 * Android can fully configure the embedded homeserver. Kept here (not on the
 * common `Config`) so UniFFI stays out of the common crates — see the
 * crate-structure rule in CLAUDE.md. Fields are required unless marked with a
 * `uniffi` default; the dev binary's defaults live in
 * `Config::default`/`from_env`.
 */
public struct NeutrinoConfig: Equatable, Hashable {
    public var bindAddr: String
    public var localpart: String
    /**
     * The homeserver's federation `server_name` — the domain in
     * `@localpart:server_name`. `None` (or an empty string) lets the server
     * derive a stable name from its node identity, which is the embedded
     * default; the host then reads the result back via
     * `NeutrinoHandle::server_name()`. Set a concrete value to pin a specific
     * name: it is recorded on first start and every later start under a
     * different name is refused (see the server-name identity guard).
     */
    public var serverName: String?
    /**
     * Absolute path to a writable directory the host owns (e.g. Android's
     * `context.filesDir`). The DB is `<storage_dir>/neutrino.db`.
     */
    public var storageDir: String
    public var outboundConcurrency: UInt32
    /**
     * Whether the network is trusted and hence whether we can drop signatures
     */
    public var trustedNetwork: Bool
    /**
     * When set, runs the in-process `neutrino-lb` CoAP low-bandwidth sidecar.
     * This is the public federation port the ingress binds — peers'
     * `server_name` resolves to `host(bind_addr):lb_federation_port`. The
     * egress is an internal loopback port the server allocates. `None` = direct
     * federation (no in-process sidecar).
     */
    public var lbFederationPort: UInt16?
    /**
     * Absolute path to a directory the server writes rotating `neutrino.*` log
     * files into, on top of logcat. Android's logcat is a small ring buffer
     * that also drops lines from chatty UIDs, so a bug report filed minutes
     * after a failure has already lost it; point this at the host's bug-report
     * log directory to keep a day of history that the report can upload. The
     * server creates the directory if missing. `None` = logcat only.
     */
    public var logDir: String?
    /**
     * Whether `/sync` surfaces synthesised delivery receipts: an `m.read`
     * receipt for a remote user once that user's server has acknowledged the
     * federation transaction carrying the event. It is a deliberate lie —
     * their server *received* it, nobody read it — so it is off unless the
     * host (or the medium's own start wrapper) asks for it. Defaulted so
     * existing callers are unaffected.
     */
    public var deliveryReceipts: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(bindAddr: String, localpart: String, 
        /**
         * The homeserver's federation `server_name` — the domain in
         * `@localpart:server_name`. `None` (or an empty string) lets the server
         * derive a stable name from its node identity, which is the embedded
         * default; the host then reads the result back via
         * `NeutrinoHandle::server_name()`. Set a concrete value to pin a specific
         * name: it is recorded on first start and every later start under a
         * different name is refused (see the server-name identity guard).
         */serverName: String?, 
        /**
         * Absolute path to a writable directory the host owns (e.g. Android's
         * `context.filesDir`). The DB is `<storage_dir>/neutrino.db`.
         */storageDir: String, outboundConcurrency: UInt32, 
        /**
         * Whether the network is trusted and hence whether we can drop signatures
         */trustedNetwork: Bool, 
        /**
         * When set, runs the in-process `neutrino-lb` CoAP low-bandwidth sidecar.
         * This is the public federation port the ingress binds — peers'
         * `server_name` resolves to `host(bind_addr):lb_federation_port`. The
         * egress is an internal loopback port the server allocates. `None` = direct
         * federation (no in-process sidecar).
         */lbFederationPort: UInt16?, 
        /**
         * Absolute path to a directory the server writes rotating `neutrino.*` log
         * files into, on top of logcat. Android's logcat is a small ring buffer
         * that also drops lines from chatty UIDs, so a bug report filed minutes
         * after a failure has already lost it; point this at the host's bug-report
         * log directory to keep a day of history that the report can upload. The
         * server creates the directory if missing. `None` = logcat only.
         */logDir: String? = nil, 
        /**
         * Whether `/sync` surfaces synthesised delivery receipts: an `m.read`
         * receipt for a remote user once that user's server has acknowledged the
         * federation transaction carrying the event. It is a deliberate lie —
         * their server *received* it, nobody read it — so it is off unless the
         * host (or the medium's own start wrapper) asks for it. Defaulted so
         * existing callers are unaffected.
         */deliveryReceipts: Bool = false) {
        self.bindAddr = bindAddr
        self.localpart = localpart
        self.serverName = serverName
        self.storageDir = storageDir
        self.outboundConcurrency = outboundConcurrency
        self.trustedNetwork = trustedNetwork
        self.lbFederationPort = lbFederationPort
        self.logDir = logDir
        self.deliveryReceipts = deliveryReceipts
    }

    

    
}

#if compiler(>=6)
extension NeutrinoConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNeutrinoConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NeutrinoConfig {
        return
            try NeutrinoConfig(
                bindAddr: FfiConverterString.read(from: &buf), 
                localpart: FfiConverterString.read(from: &buf), 
                serverName: FfiConverterOptionString.read(from: &buf), 
                storageDir: FfiConverterString.read(from: &buf), 
                outboundConcurrency: FfiConverterUInt32.read(from: &buf), 
                trustedNetwork: FfiConverterBool.read(from: &buf), 
                lbFederationPort: FfiConverterOptionUInt16.read(from: &buf), 
                logDir: FfiConverterOptionString.read(from: &buf), 
                deliveryReceipts: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: NeutrinoConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.bindAddr, into: &buf)
        FfiConverterString.write(value.localpart, into: &buf)
        FfiConverterOptionString.write(value.serverName, into: &buf)
        FfiConverterString.write(value.storageDir, into: &buf)
        FfiConverterUInt32.write(value.outboundConcurrency, into: &buf)
        FfiConverterBool.write(value.trustedNetwork, into: &buf)
        FfiConverterOptionUInt16.write(value.lbFederationPort, into: &buf)
        FfiConverterOptionString.write(value.logDir, into: &buf)
        FfiConverterBool.write(value.deliveryReceipts, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNeutrinoConfig_lift(_ buf: RustBuffer) throws -> NeutrinoConfig {
    return try FfiConverterTypeNeutrinoConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNeutrinoConfig_lower(_ value: NeutrinoConfig) -> RustBuffer {
    return FfiConverterTypeNeutrinoConfig.lower(value)
}


/**
 * Failure arming a pcap capture (see `NeutrinoHandle::start_capture`).
 */
public enum CaptureError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * The capture file could not be opened/created at the given path. Field is
     * named `reason` (not `message`) to avoid colliding with `Throwable.message`
     * in the generated Kotlin exception.
     */
    case Io(reason: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension CaptureError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCaptureError: FfiConverterRustBuffer {
    typealias SwiftType = CaptureError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CaptureError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Io(
            reason: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CaptureError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Io(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCaptureError_lift(_ buf: RustBuffer) throws -> CaptureError {
    return try FfiConverterTypeCaptureError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCaptureError_lower(_ value: CaptureError) -> RustBuffer {
    return FfiConverterTypeCaptureError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * FFI-facing control command. Mirrors `neutrino_ctl::Command` (re-exported
 * as `neutrino_main::Command`) so EX Android can drive the embedded server.
 * Kept here, not on the common `Command`, so UniFFI stays out of the common
 * crates — the same split as `NeutrinoConfig` / `Config`.
 */

public enum Command: Equatable, Hashable {
    
    case shutdown
    case kickBackoff





}

#if compiler(>=6)
extension Command: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCommand: FfiConverterRustBuffer {
    typealias SwiftType = Command

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Command {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .shutdown
        
        case 2: return .kickBackoff
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Command, into buf: inout [UInt8]) {
        switch value {
        
        
        case .shutdown:
            writeInt(&buf, Int32(1))
        
        
        case .kickBackoff:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCommand_lift(_ buf: RustBuffer) throws -> Command {
    return try FfiConverterTypeCommand.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCommand_lower(_ value: Command) -> RustBuffer {
    return FfiConverterTypeCommand.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt16: FfiConverterRustBuffer {
    typealias SwiftType = UInt16?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt16.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt16.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDiscoveredPeer: FfiConverterRustBuffer {
    typealias SwiftType = [DiscoveredPeer]

    public static func write(_ value: [DiscoveredPeer], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDiscoveredPeer.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DiscoveredPeer] {
        let len: Int32 = try readInt(&buf)
        var seq = [DiscoveredPeer]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDiscoveredPeer.read(from: &buf))
        }
        return seq
    }
}
/**
 * Spawn an owned Tokio runtime and begin polling the server entrypoint with
 * the supplied configuration. Returns a handle for pushing control commands
 * (including `Shutdown`) into the running server. When the server stops
 * (via `Shutdown` or channel close) the runtime is dropped on its OS thread:
 * the executor stops and async tasks are cancelled at their next await point,
 * but joining the blocking pool waits for any in-flight SQLite write to finish
 * — those `spawn_blocking` closures are non-cancellable (`neutrino-store-sqlite`
 * `WRITE_TIMEOUT` surfaces a hung write to its awaiter but does not stop the
 * closure). Normal writes are sub-millisecond, so teardown is effectively
 * immediate; only a runaway closure can delay this thread's exit.
 */
public func start(config: NeutrinoConfig) -> NeutrinoHandle  {
    return try!  FfiConverterTypeNeutrinoHandle_lift(try! rustCall() {
    uniffi_neutrino_fn_func_start(
        FfiConverterTypeNeutrinoConfig_lower(config),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_neutrino_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_neutrino_checksum_func_start() != 41467) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neutrino_checksum_method_neutrinohandle_command() != 63006) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neutrino_checksum_method_neutrinohandle_discovered_peers() != 54574) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neutrino_checksum_method_neutrinohandle_is_capturing() != 16330) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neutrino_checksum_method_neutrinohandle_kick_backoff() != 7625) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neutrino_checksum_method_neutrinohandle_last_error() != 37043) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neutrino_checksum_method_neutrinohandle_server_name() != 61779) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neutrino_checksum_method_neutrinohandle_shutdown() != 40851) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neutrino_checksum_method_neutrinohandle_start_capture() != 29001) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_neutrino_checksum_method_neutrinohandle_stop_capture() != 49157) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureNeutrinoInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all